### PR TITLE
Add support for Mac

### LINKED ISSUE #21: Enable Transcribe to work on Mac
Transcribe currently only works on Windows. 
Enable transcribe to work on Mac as well.

### PR DESCRIPTION
**Pull request by vivekuppal**
- Add support for Mac

Resolves #21

### CODE REVIEW

**Comment by DawgZter** [comment]
Hey thanks for your work on this @vivekuppal! I'm just wondering if there happens to be an eta on when we can see this closed?

**Comment by vivekuppal** [comment]
Thanks for bringing this to my attention :-).

Base branch has moved forward a fair amount since these changes were made originally and there are still some issues to work through. 
It would be great to get a pulse in the community about the demand for Mac work and may be see some community contributions on this effort as well. I get pinged a fair amount for windows Transcribe. Haven't seen as much demand for mac at least in the folks talking to me or in public forums for Transcribe.

If people start upvoting this PR or #21 I can look at it again.

**Comment by DawgZter** [comment]
@vivekuppal Fair enough! Thank you for your continued work on this project! 
And to whoever is reading this reply and has a mac interested in using the project please upvote the PR! haha

**Comment by DawgZter** [comment]
@vivekuppal Hey just quickly bumping this. Wondering around how many upvotes you would need to action this ticket? 👀

**Comment by vivekuppal** [comment]
I would appreciate some community contributions towards the mac effort. I will contribute as well.

**Pull request closed without merging**
